# Generated by Django 5.2 on 2025-04-30 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_alter_crop_image'),
        ('field', '0002_alter_field_size_in_acres'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='crop',
            field=models.ForeignKey(default='7b370602-9d3d-4b30-8f12-30da939b3499', on_delete=django.db.models.deletion.CASCADE, related_name='crop', to='farm.crop'),
            preserve_default=False,
        ),
    ]
