# Generated by Django 5.2 on 2025-04-30 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_alter_crop_image'),
        ('field', '0003_field_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop', to='farm.crop'),
        ),
    ]
