# Generated by Django 5.2 on 2025-04-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('FarmManager', 'FarmManager'), ('FarmWorker', 'FarmWorker')], default='user', max_length=50),
        ),
    ]
