# Generated by Django 5.2 on 2025-04-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('FarmManager', 'FarmManager'), ('FarmWorker', 'FarmWorker')], default='Owner', max_length=50),
        ),
    ]
