# Generated by Django 5.2 on 2025-04-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
