# Generated by Django 5.2 on 2025-04-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.TextField(blank=True, default='maintenance'),
        ),
    ]
