# Generated by Django 5.2 on 2025-04-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='farm',
            name='image',
            field=models.FileField(default='sss', upload_to='images/'),
            preserve_default=False,
        ),
    ]
