# Generated by Django 5.2 on 2025-04-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_remove_farm_created_at_remove_farm_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='size_in_acres',
            field=models.FloatField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
