# Generated by Django 5.2 on 2025-04-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_farm_size_in_acres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='size_in_acres',
            field=models.FloatField(),
        ),
    ]
