# Generated by Django 5.2 on 2025-04-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.CharField(max_length=400),
        ),
    ]
