services:
  db:
    image: postgres:16
    container_name: drf_postgres
    restart: always
    environment:
      POSTGRES_DB: postgres 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

